### ISSUE TITLE
Is it possible to add a new service to a provider on the fly ?

### ISSUE THREAD

**Issue by seandelaney** [verbb/postie#87] opened 2022-02-24 13:43 UTC
**What are you trying to do?**
A description of what you want to happen.

I've got a few providers setup in the postie config file. Each provider has an array of services.

Is it possible to add a new service to a provider on the fly ?

**Comment by engram-design** [comment] 2022-02-25 05:59
Duplicate of https://github.com/verbb/postie/issues/86

**Closed as completed** 2022-02-25 05:58 UTC
Labels: feature request
